# Generated by Django 2.1 on 2018-09-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='curriculum_vitae',
            field=models.FileField(default='Not Found', upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='identity_card',
            field=models.CharField(default='Not Found', max_length=20),
            preserve_default=False,
        ),
    ]
