# Generated by Django 2.1 on 2018-09-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0003_auto_20180902_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
    ]
