# Generated by Django 2.1 on 2018-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0005_informationcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost_course',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='introduce',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationcenter',
            name='center_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationcenter',
            name='hotline',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
