# Generated by Django 2.1 on 2018-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0006_auto_20180905_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_open',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
