# Generated by Django 2.1 on 2018-09-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0007_course_time_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_1', models.TextField()),
                ('information_2', models.TextField()),
                ('information_3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InformationIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_1', models.TextField()),
                ('information_2', models.TextField()),
                ('information_3', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='curriculum_vitae',
            field=models.FileField(default='Not Found', upload_to='documents'),
        ),
    ]
