# Generated by Django 2.1 on 2018-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0008_auto_20180906_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='curriculum_vitae',
            field=models.FileField(default='Not Found', upload_to=''),
        ),
    ]
