# Generated by Django 2.1 on 2018-09-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0009_auto_20180906_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationindex',
            name='slide_picture_1',
            field=models.ImageField(default='null', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationindex',
            name='slide_picture_2',
            field=models.ImageField(default='null', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationindex',
            name='slide_picture_3',
            field=models.ImageField(default='null', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='curriculum_vitae',
            field=models.FileField(default='Not Found', upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image_teacher',
            field=models.ImageField(upload_to='images'),
        ),
    ]
