# Generated by Django 2.1 on 2018-09-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0010_auto_20180907_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationindex',
            name='information_1',
        ),
        migrations.RemoveField(
            model_name='informationindex',
            name='information_2',
        ),
        migrations.AddField(
            model_name='informationindex',
            name='content_title_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='informationindex',
            name='content_title_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='informationindex',
            name='information_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='informationindex',
            name='title_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informationindex',
            name='title_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informationindex',
            name='title_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informationindex',
            name='title_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informationindex',
            name='information_3',
            field=models.TextField(null=True),
        ),
    ]
