# Generated by Django 2.1 on 2018-09-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishcenter', '0012_auto_20180907_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationindex',
            name='slide_picture_1',
        ),
        migrations.RemoveField(
            model_name='informationindex',
            name='slide_picture_2',
        ),
        migrations.RemoveField(
            model_name='informationindex',
            name='slide_picture_3',
        ),
    ]
